language: php
php:
    - '7.1'
before_script:
    - sudo apt-get install libssh2-1-dev
    - printf "\n" | pecl install ssh2-1.0
    - composer install -n
after_script:
    - bash <(curl -s https://codecov.io/bash)
