# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    linode.api:
        class: AppBundle\Service\LinodeApiService
        arguments: ["%linode.token%"]

    linode.form.create:
        class: AppBundle\Form\CreateLinodeType
        arguments: ["@linode.api.avail"]
        tags:
            - { name: form.type }

    linode.form.clone:
        class: AppBundle\Form\CloneType
        arguments: ["@linode.api.avail", "@linode.api.host"]
        tags:
            - { name: form.type }

    linode.api.host:
        class: AppBundle\Service\LinodeHostService
        arguments: ["@linode.api"]

    linode.api.avail:
        class: AppBundle\Service\LinodeAvailService
        arguments: ["@linode.api"]

    linode.api.ip:
        class: AppBundle\Service\LinodeIpService
        arguments: ["@linode.api"]
