# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    linode.api:
        class: AppBundle\Service\LinodeApiService
        arguments: ["%linode.token%"]

    linode.form.create:
        class: AppBundle\Form\CreateLinodeType
        arguments: ["@linode.api"]

    linode.api.list:
        class: AppBundle\Service\LinodeListService
        arguments: ["@linode.api"]
